servizi:
  - tipo: web
    nome: MammaMia  
    tempo di esecuzione: python  
    buildCommand: pip install -r requirements.txt  
    startCommand: python3 run.py  
    piano: gratuito
    regione: Francoforte
    variabiliambiente:
      # Imposta un valore hardcoded
      # (NON codificare i segreti nel tuo file Blueprint!)
      - chiave: PORT
        valore: 8080
      # Richiede un valore nella Dashboard di rendering durante la creazione
      # (utile per i segreti)
      - chiave: TMDB_KEY
        sincronizzazione: falso
      - chiave: PROXY
        sincronizzazione: falso
